### ISSUE TITLE
Ревью 14.07

### ISSUE THREAD

**Issue by d3ple** [shimkek/verstka#1]
### HTML

1. https://github.com/shimkek/verstka/blob/ccb481cea0ca2ca685604b6e98cd59b287e9cf68/yandexclone/src/index.html#L13
Называй короче, page-header это излишне, можно просто header

2. https://github.com/shimkek/verstka/blob/ccb481cea0ca2ca685604b6e98cd59b287e9cf68/yandexclone/src/index.html#L18
Не понимаю почему у тебя везде модификаторы, хотя это элемент

3. https://github.com/shimkek/verstka/blob/ccb481cea0ca2ca685604b6e98cd59b287e9cf68/yandexclone/src/index.html#L53
Тут например option это элемент, а chosen это модификатор, а у тебя они одинаково выделяются

4. https://github.com/shimkek/verstka/blob/ccb481cea0ca2ca685604b6e98cd59b287e9cf68/yandexclone/src/index.html#L4
Добавь мета теги

5. https://github.com/shimkek/verstka/blob/ccb481cea0ca2ca685604b6e98cd59b287e9cf68/yandexclone/src/index.html#L16
У изображений должен быть атрибут alt

### CSS

1. https://github.com/shimkek/verstka/blob/ccb481cea0ca2ca685604b6e98cd59b287e9cf68/yandexclone/src/styles.css
Создай папку styles и разбей этот большой файл на много файлов, где каждый файл это один блок
И один файл index.css, где все эти файлы импортнешь. Можно использовать чистый css, можно scss, можно postcss, что понравится. Я использую scss и у всех файлов соответственно расширение scss.

2. Если будешь использовать scss, то там удобно работать со вложенностью, например:
```
.header {...}
.header__banner {...}
.header__link {...}
.header__link_active {...}
```
Можно переписать так:
```
.header {
    &__banner {...}

    &__link {
          ...
         &_active {...}
    }
}
```

3. https://github.com/shimkek/verstka/blob/ccb481cea0ca2ca685604b6e98cd59b287e9cf68/yandexclone/src/styles.css#L63
Ты видимо не понял что такое блок, перечитай. У блока нет отступов, бывает что нет и ширины и высоты. Смысл блока, чтоб ты просто мог скопировать его в другое место. С отступами ты не сможешь его просто скопировать.
Отступы нужно задавать у элемента. Компонент может быть и блоком и элементом, навешиваешь просто два класса:
```
<div class="header__baner baner"></div>
```
У header__baner задаешь отступы, у baner стили баннера

4. Если где-то повторяются одни и теже цвета, то вынеси их в переменные, размеры шрифта, жирность тоже.

5. https://github.com/shimkek/verstka/blob/ccb481cea0ca2ca685604b6e98cd59b287e9cf68/yandexclone/src/styles.css#L11
Не нужно задавать стили тегам, ты сбросил все что нужно в normalize.css и больше тэги не трогай. Все через классы делай, классов же может быть сколько угодно, например:
```
<button class="button header__button">Кнопка</button>
```

**Comment by shimkek** [comment]
> щас решим
